# Generated by Django 6.0 on 2026-06-30 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashsession',
            name='suspended_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='cashsession',
            name='status',
            field=models.CharField(choices=[('open', 'Abierta'), ('suspended', 'Suspendida'), ('closed', 'Cerrada')], default='open', max_length=12),
        ),
    ]
