# Generated by Django 6.0 on 2026-06-30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '0002_cashsession_suspended_at_alter_cashsession_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashSessionClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closed_at', models.DateTimeField(auto_now_add=True)),
                ('expected_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('counted_amount', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('difference', models.DecimalField(decimal_places=2, default='0.00', max_digits=12)),
                ('notes', models.TextField(blank=True, default='')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='closures', to='cash.cashsession')),
            ],
            options={
                'ordering': ['-closed_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cashsessionclosure',
            index=models.Index(fields=['session', '-closed_at'], name='cash_cashse_session_idx'),
        ),
    ]
