# Generated by Django 6.0 on 2026-05-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('manager', 'Gerente'), ('cashier', 'Cajero')], default='cashier', max_length=20, verbose_name='Role'),
        ),
    ]
