# Generated by Django 6.0 on 2026-03-23 16:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_percentage', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=0)),
                ('surcharge_percentage', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=0)),
                ('surcharge_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, choices=[('pending', 'Pendiente'), ('completed', 'Completado'), ('canceled', 'Cancelado')], default='pending', max_length=50, null=True)),
                ('payment_type', models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('credit_card', 'Tarjeta de Crédito'), ('debit_card', 'Tarjeta de Débito'), ('bank_transfer', 'Transferencia Bancaria')], default='cash', max_length=50, null=True)),
                ('sale_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('product', 'Producto'), ('service', 'Servicio')], default='product', max_length=10)),
                ('subtotal', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
                ('discount_percentage', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=0)),
                ('surcharge_percentage', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (15, '15%'), (20, '20%')], default=0)),
                ('surcharge_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('price_per_item', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
            ],
        ),
    ]
