# Generated by Django 6.0 on 2026-05-06 18:00

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_presentation_and_decimal_stock'),
        ('sales', '0002_alter_sale_discount_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='presentation',
            field=models.ForeignKey(blank=True, help_text='Presentación seleccionada al momento de la venta', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.productpresentation'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='presentation_multiplier_snap',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), help_text='Multiplicador usado para calcular el descuento de stock', max_digits=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='presentation_name',
            field=models.CharField(blank=True, help_text='Nombre de la presentación en el momento de la venta', max_length=100),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='presentation_price_snapshot',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Precio de la presentación en el momento de la venta', max_digits=10),
        ),
        migrations.AlterField(
            model_name='saleitem',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=Decimal('1.0000'), max_digits=10),
        ),
    ]
