# Generated by Django 6.0 on 2026-05-28 01:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cash', '__first__'),
        ('sales', '0003_add_presentation_to_saleitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='cash_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='cash.cashsession'),
        ),
    ]
