# Generated by Django 6.0 on 2026-06-01 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_rename_cancelled_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='parent_service_item',
            field=models.ForeignKey(blank=True, help_text='If this is a supply item, references the parent service SaleItem', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplies', to='sales.saleitem'),
        ),
    ]
