# Generated by Django 6.0 on 2026-07-30 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_alter_sale_payment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='payment_type',
            field=models.CharField(blank=True, choices=[('cash', 'Efectivo'), ('card', 'Tarjeta'), ('transfer', 'Transferencia'), ('credit', 'Crédito')], default='cash', max_length=50, null=True),
        ),
    ]
