# Generated by Django 6.0 on 2026-05-06 17:59

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='base_unit',
            field=models.CharField(default='u', help_text='Unidad de medida base (ej: lb, kg, ml, u, caja)', max_length=20),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='new_stock',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='previous_stock',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='inventorymovement',
            name='quantity',
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), help_text='Stock disponible expresado en base_unit', max_digits=12),
        ),
        migrations.CreateModel(
            name='ProductPresentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Nombre descriptivo (ej: 'Saco 100lb', 'Unidad', 'Botella 500ml')", max_length=100)),
                ('multiplier', models.DecimalField(decimal_places=4, help_text='Cuántas unidades base representa esta presentación', max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, help_text='Precio de venta de esta presentación', max_digits=10)),
                ('barcode', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presentations', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'name')},
            },
        ),
    ]
