# Generated by Django 6.0 on 2026-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_add_presentation_and_decimal_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='base_unit',
            field=models.CharField(choices=[('u', 'Unidad'), ('kg', 'Kilogramo'), ('g', 'Gramo'), ('lb', 'Libra'), ('ml', 'Mililitro'), ('l', 'Litro'), ('caja', 'Caja')], default='u', help_text='Unidad de medida base (ej: lb, kg, ml, u, caja)', max_length=20),
        ),
    ]
