# Generated by Django 6.0 on 2026-05-22 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_product_base_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorymovement',
            name='presentation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_movements', to='products.productpresentation'),
        ),
    ]
