# Generated by Django 6.0 on 2026-07-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_movementbatch_inventorymovement_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_sale_product',
            field=models.BooleanField(default=True, help_text='Aparece como producto de venta directa.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_service_supply',
            field=models.BooleanField(default=False, help_text='Aparece como insumo de un servicio en la venta.'),
        ),
    ]
